version: "3"
services:
  compass:
    restart: always
    image: iqtlabs/pibackbone-compass:${SERVICES_IMAGE_TAG:-stable}
    networks:
      - pibackbone
    environment:
      - "HOSTNAME=${HOSTNAME}"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - '8000:8000'
networks:
    pibackbone:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 900
