version: "3"
services:
  hifiberry-dac-plus-adc-pro:
    image: iqtlabs/pibackbone-hifiberry-dac-plus-adc-pro:${SERVICES_IMAGE_TAG:-stable}
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/hydrophone:/flash/telemetry/hydrophone"
    devices:
      - "/dev/snd:/dev/snd"
